version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: finance
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 3000:3000
    links:
      - redis
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  redis:
    image: redis
    command: redis-server --appendonly yes --appendfsync everysec
    ports:
      - "6379:6379"
  db:
    image: postgres:13.4-buster
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - finance_data:/var/lib/postgresql/data
volumes:
  finance_data:
  