r = Redis.new(host: "redis")

r.mapped_hmset('account:9', {'id':"9", 'name':"Nubank", 'balance':"6940.0", 'user_id':"1"})
r.mapped_hmset('account:10', {'id':"10", 'name':"Vale Alimentação", 'balance':"3177.0", 'user_id':"1"})
r.mapped_hmset('account:11', {'id':"11", 'name':"Cofre", 'balance':"5300.0", 'user_id':"1"})
r.mapped_hmset('account:12', {'id':"12", 'name':"Pague Mais", 'balance':"642.0", 'user_id':"1"})

r.mapped_hmset('category:11', {'id':"11", 'name':"Mercado", 'user_id':"1"})
r.mapped_hmset('category:12', {'id':"12", 'name':"Lazer", 'user_id':"1"})
r.mapped_hmset('category:13', {'id':"13", 'name':"Assinaturas", 'user_id':"1"})
r.mapped_hmset('category:14', {'id':"14", 'name':"Contas", 'user_id':"1"})
r.mapped_hmset('category:15', {'id':"15", 'name':"Loteria", 'user_id':"1"})
r.mapped_hmset('category:16', {'id':"16", 'name':"Carro", 'user_id':"1"})
r.mapped_hmset('category:17', {'id':"17", 'name':"Transporte", 'user_id':"1"})
r.mapped_hmset('category:18', {'id':"18", 'name':"Salário", 'user_id':"1"})
r.mapped_hmset('category:19', {'id':"19", 'name':"Transferência pro cofre", 'user_id':"1"})

r.mapped_hmset('installment:5', {'id':"5", 'name':"Aquisição do celta preto", 'description':"Juntando dinheiro pra comprar o vrum vrum que diz o tempo", 'planned_expense':"12000.0", 'user_id':"1"})
r.mapped_hmset('installment:6', {'id':"6", 'name':"Lanche na faculdade", 'description':"Dinheiro que pode gastar por mês na faculdade", 'planned_expense':"300.0", 'user_id':"1"})
r.mapped_hmset('installment:7', {'id':"7", 'name':"Terno pro casamento do Romeu", 'description':"Compra do terno para o casamento do meu primo de terceiro grau (tem que comprar, o negócio que aluga fechou)", 'planned_expense':"200.0", 'user_id':"1"})

r.mapped_hmset('entry:37', {'id':"37", 'title':"Sapato", 'description':"Sapato do terno", 'account_id':"9", 'value':"40.0", 'type_id':"1", 'category_id':"12", 'installment_id':"7", 'date':"2022-07-28"})        
r.mapped_hmset('entry:38', {'id':"38", 'title':"Meias sociais", 'description':"Meias para usar com os sapatos no casamento", 'account_id':"9", 'value':"10.0", 'type_id':"1", 'category_id':"12", 'installment_id':"7", 'date':"2022-07-27"})                                                                              
r.mapped_hmset('entry:39', {'id':"39", 'title':"Tuxedo", 'description':"Tuxedo do terno", 'account_id':"9", 'value':"110.0", 'type_id':"1", 'category_id':"12", 'installment_id':"7", 'date':"2022-07-26"})
r.mapped_hmset('entry:40', {'id':"40", 'title':"Salário", 'description':"", 'account_id':"9", 'value':"2600.0", 'type_id':"2", 'category_id':"18", 'installment_id':"", 'date':"2022-06-30"})                     
r.mapped_hmset('entry:41', {'id':"41", 'title':"Enrolado de frango", 'description':"lanche na faculdade",'account_id':"10", 'value':"4.0", 'type_id':"1", 'category_id':"11", 'installment_id':"6", 'date':"2022-07-01"})                                                                                                 
r.mapped_hmset('entry:42', {'id':"42", 'title':"Croissant", 'description':"lanche na udesc", 'account_id':"10", 'value':"5.0", 'type_id':"1", 'category_id':"11", 'installment_id':"6", 'date':"2022-07-04"})     
r.mapped_hmset('entry:43', {'id':"43", 'title':"Batata pra piazada", 'description':"Happy hour cos guri", 'account_id':"10", 'value':"60.0", 'type_id':"1", 'category_id':"12", 'installment_id':"", 'date':"2022-07-27"})                                                                                                 
r.mapped_hmset('entry:44', {'id':"44", 'title':"Sanduba", 'description':"", 'account_id':"10", 'value':"4.0", 'type_id':"1", 'category_id':"11", 'installment_id':"6", 'date':"2022-07-05"})                      
r.mapped_hmset('entry:45', {'id':"45", 'title':"Vale alimentação", 'description':"", 'account_id':"10", 'value':"600.0", 'type_id':"2", 'category_id':"18", 'installment_id':"", 'date':"2022-07-01"})            
r.mapped_hmset('entry:46', {'id':"46", 'title':"Transferência pro cofre", 'description':"", 'account_id':"9", 'value':"500.0", 'type_id':"1", 'category_id':"19", 'installment_id':"", 'date':"2022-06-30"})      
r.mapped_hmset('entry:47', {'id':"47", 'title':"Transferência pro cofre", 'description':"", 'account_id':"11", 'value':"500.0", 'type_id':"2", 'category_id':"19", 'installment_id':"", 'date':"2022-06-30"})